// Code generated by protoc-gen-gogo.
// source: event.proto
// DO NOT EDIT!

/*
	Package orchestrator is a generated protocol buffer package.

	It is generated from these files:
		event.proto

	It has these top-level messages:
		Event
		Work
*/
package orchestrator

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Event_Level int32

const (
	Event_BATCH Event_Level = 0
	Event_JOB   Event_Level = 1
)

var Event_Level_name = map[int32]string{
	0: "BATCH",
	1: "JOB",
}
var Event_Level_value = map[string]int32{
	"BATCH": 0,
	"JOB":   1,
}

func (x Event_Level) String() string {
	return proto.EnumName(Event_Level_name, int32(x))
}
func (Event_Level) EnumDescriptor() ([]byte, []int) { return fileDescriptorEvent, []int{0, 0} }

type Event_Status int32

const (
	Event_MISSING Event_Status = 0
	Event_PENDING Event_Status = 1
	Event_RUNNING Event_Status = 2
	Event_SUCCESS Event_Status = 3
	Event_FAILURE Event_Status = 4
)

var Event_Status_name = map[int32]string{
	0: "MISSING",
	1: "PENDING",
	2: "RUNNING",
	3: "SUCCESS",
	4: "FAILURE",
}
var Event_Status_value = map[string]int32{
	"MISSING": 0,
	"PENDING": 1,
	"RUNNING": 2,
	"SUCCESS": 3,
	"FAILURE": 4,
}

func (x Event_Status) String() string {
	return proto.EnumName(Event_Status_name, int32(x))
}
func (Event_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptorEvent, []int{0, 1} }

type Event struct {
	BatchId     []byte            `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	JobId       int32             `protobuf:"varint,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	StatusLevel Event_Level       `protobuf:"varint,3,opt,name=status_level,json=statusLevel,proto3,enum=orchestrator.Event_Level" json:"status_level,omitempty"`
	Status      Event_Status      `protobuf:"varint,4,opt,name=status,proto3,enum=orchestrator.Event_Status" json:"status,omitempty"`
	Parameters  *Event_Parameters `protobuf:"bytes,5,opt,name=parameters" json:"parameters,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptorEvent, []int{0} }

func (m *Event) GetBatchId() []byte {
	if m != nil {
		return m.BatchId
	}
	return nil
}

func (m *Event) GetJobId() int32 {
	if m != nil {
		return m.JobId
	}
	return 0
}

func (m *Event) GetStatusLevel() Event_Level {
	if m != nil {
		return m.StatusLevel
	}
	return Event_BATCH
}

func (m *Event) GetStatus() Event_Status {
	if m != nil {
		return m.Status
	}
	return Event_MISSING
}

func (m *Event) GetParameters() *Event_Parameters {
	if m != nil {
		return m.Parameters
	}
	return nil
}

type Event_Parameters struct {
	JobCount     int32   `protobuf:"varint,1,opt,name=job_count,json=jobCount,proto3" json:"job_count,omitempty"`
	MeanDuration int64   `protobuf:"varint,2,opt,name=mean_duration,json=meanDuration,proto3" json:"mean_duration,omitempty"`
	FailureRate  float32 `protobuf:"fixed32,3,opt,name=failure_rate,json=failureRate,proto3" json:"failure_rate,omitempty"`
}

func (m *Event_Parameters) Reset()                    { *m = Event_Parameters{} }
func (m *Event_Parameters) String() string            { return proto.CompactTextString(m) }
func (*Event_Parameters) ProtoMessage()               {}
func (*Event_Parameters) Descriptor() ([]byte, []int) { return fileDescriptorEvent, []int{0, 0} }

func (m *Event_Parameters) GetJobCount() int32 {
	if m != nil {
		return m.JobCount
	}
	return 0
}

func (m *Event_Parameters) GetMeanDuration() int64 {
	if m != nil {
		return m.MeanDuration
	}
	return 0
}

func (m *Event_Parameters) GetFailureRate() float32 {
	if m != nil {
		return m.FailureRate
	}
	return 0
}

type Work struct {
	BatchId     []byte  `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	JobId       int32   `protobuf:"varint,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Duration    int64   `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	FailureRate float32 `protobuf:"fixed32,4,opt,name=failure_rate,json=failureRate,proto3" json:"failure_rate,omitempty"`
}

func (m *Work) Reset()                    { *m = Work{} }
func (m *Work) String() string            { return proto.CompactTextString(m) }
func (*Work) ProtoMessage()               {}
func (*Work) Descriptor() ([]byte, []int) { return fileDescriptorEvent, []int{1} }

func (m *Work) GetBatchId() []byte {
	if m != nil {
		return m.BatchId
	}
	return nil
}

func (m *Work) GetJobId() int32 {
	if m != nil {
		return m.JobId
	}
	return 0
}

func (m *Work) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Work) GetFailureRate() float32 {
	if m != nil {
		return m.FailureRate
	}
	return 0
}

func init() {
	proto.RegisterType((*Event)(nil), "orchestrator.Event")
	proto.RegisterType((*Event_Parameters)(nil), "orchestrator.Event.Parameters")
	proto.RegisterType((*Work)(nil), "orchestrator.Work")
	proto.RegisterEnum("orchestrator.Event_Level", Event_Level_name, Event_Level_value)
	proto.RegisterEnum("orchestrator.Event_Status", Event_Status_name, Event_Status_value)
}
func (m *Event) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Event) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.BatchId) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintEvent(dAtA, i, uint64(len(m.BatchId)))
		i += copy(dAtA[i:], m.BatchId)
	}
	if m.JobId != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintEvent(dAtA, i, uint64(m.JobId))
	}
	if m.StatusLevel != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintEvent(dAtA, i, uint64(m.StatusLevel))
	}
	if m.Status != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintEvent(dAtA, i, uint64(m.Status))
	}
	if m.Parameters != nil {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintEvent(dAtA, i, uint64(m.Parameters.Size()))
		n1, err := m.Parameters.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	return i, nil
}

func (m *Event_Parameters) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Event_Parameters) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.JobCount != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintEvent(dAtA, i, uint64(m.JobCount))
	}
	if m.MeanDuration != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintEvent(dAtA, i, uint64(m.MeanDuration))
	}
	if m.FailureRate != 0 {
		dAtA[i] = 0x1d
		i++
		i = encodeFixed32Event(dAtA, i, uint32(math.Float32bits(float32(m.FailureRate))))
	}
	return i, nil
}

func (m *Work) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Work) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.BatchId) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintEvent(dAtA, i, uint64(len(m.BatchId)))
		i += copy(dAtA[i:], m.BatchId)
	}
	if m.JobId != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintEvent(dAtA, i, uint64(m.JobId))
	}
	if m.Duration != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintEvent(dAtA, i, uint64(m.Duration))
	}
	if m.FailureRate != 0 {
		dAtA[i] = 0x25
		i++
		i = encodeFixed32Event(dAtA, i, uint32(math.Float32bits(float32(m.FailureRate))))
	}
	return i, nil
}

func encodeFixed64Event(dAtA []byte, offset int, v uint64) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	dAtA[offset+4] = uint8(v >> 32)
	dAtA[offset+5] = uint8(v >> 40)
	dAtA[offset+6] = uint8(v >> 48)
	dAtA[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Event(dAtA []byte, offset int, v uint32) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintEvent(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Event) Size() (n int) {
	var l int
	_ = l
	l = len(m.BatchId)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.JobId != 0 {
		n += 1 + sovEvent(uint64(m.JobId))
	}
	if m.StatusLevel != 0 {
		n += 1 + sovEvent(uint64(m.StatusLevel))
	}
	if m.Status != 0 {
		n += 1 + sovEvent(uint64(m.Status))
	}
	if m.Parameters != nil {
		l = m.Parameters.Size()
		n += 1 + l + sovEvent(uint64(l))
	}
	return n
}

func (m *Event_Parameters) Size() (n int) {
	var l int
	_ = l
	if m.JobCount != 0 {
		n += 1 + sovEvent(uint64(m.JobCount))
	}
	if m.MeanDuration != 0 {
		n += 1 + sovEvent(uint64(m.MeanDuration))
	}
	if m.FailureRate != 0 {
		n += 5
	}
	return n
}

func (m *Work) Size() (n int) {
	var l int
	_ = l
	l = len(m.BatchId)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.JobId != 0 {
		n += 1 + sovEvent(uint64(m.JobId))
	}
	if m.Duration != 0 {
		n += 1 + sovEvent(uint64(m.Duration))
	}
	if m.FailureRate != 0 {
		n += 5
	}
	return n
}

func sovEvent(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozEvent(x uint64) (n int) {
	return sovEvent(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Event) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Event: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Event: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BatchId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BatchId = append(m.BatchId[:0], dAtA[iNdEx:postIndex]...)
			if m.BatchId == nil {
				m.BatchId = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field JobId", wireType)
			}
			m.JobId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.JobId |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StatusLevel", wireType)
			}
			m.StatusLevel = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StatusLevel |= (Event_Level(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= (Event_Status(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Parameters", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Parameters == nil {
				m.Parameters = &Event_Parameters{}
			}
			if err := m.Parameters.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Event_Parameters) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Parameters: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Parameters: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field JobCount", wireType)
			}
			m.JobCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.JobCount |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MeanDuration", wireType)
			}
			m.MeanDuration = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MeanDuration |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field FailureRate", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 4
			v = uint32(dAtA[iNdEx-4])
			v |= uint32(dAtA[iNdEx-3]) << 8
			v |= uint32(dAtA[iNdEx-2]) << 16
			v |= uint32(dAtA[iNdEx-1]) << 24
			m.FailureRate = float32(math.Float32frombits(v))
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Work) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Work: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Work: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BatchId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BatchId = append(m.BatchId[:0], dAtA[iNdEx:postIndex]...)
			if m.BatchId == nil {
				m.BatchId = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field JobId", wireType)
			}
			m.JobId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.JobId |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Duration", wireType)
			}
			m.Duration = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Duration |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field FailureRate", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 4
			v = uint32(dAtA[iNdEx-4])
			v |= uint32(dAtA[iNdEx-3]) << 8
			v |= uint32(dAtA[iNdEx-2]) << 16
			v |= uint32(dAtA[iNdEx-1]) << 24
			m.FailureRate = float32(math.Float32frombits(v))
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvent(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthEvent
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowEvent
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipEvent(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthEvent = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvent   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("event.proto", fileDescriptorEvent) }

var fileDescriptorEvent = []byte{
	// 391 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x4f, 0x6f, 0xd3, 0x30,
	0x18, 0xc6, 0xeb, 0xe6, 0x4f, 0xbb, 0x37, 0x01, 0x45, 0x96, 0x90, 0xb2, 0x4e, 0x8a, 0x42, 0xb8,
	0xe4, 0x94, 0x43, 0xb9, 0x22, 0xa4, 0x35, 0x0b, 0x10, 0x34, 0xc2, 0xe4, 0x50, 0x71, 0x8c, 0x9c,
	0xc6, 0x68, 0x2d, 0x5d, 0x3c, 0x1c, 0x67, 0x7c, 0x0d, 0x3e, 0x15, 0xe2, 0xc8, 0x47, 0x40, 0xe5,
	0x8b, 0x20, 0x3b, 0x55, 0x99, 0xb4, 0x9e, 0x76, 0xfc, 0xbd, 0xef, 0xf3, 0x24, 0xfa, 0xd9, 0x06,
	0x87, 0xdd, 0xb1, 0x56, 0x26, 0xb7, 0x82, 0x4b, 0x8e, 0x5d, 0x2e, 0x56, 0xd7, 0xac, 0x93, 0x82,
	0x4a, 0x2e, 0xa2, 0x9f, 0x06, 0x58, 0x99, 0xda, 0xe2, 0x53, 0x98, 0xd6, 0x54, 0xae, 0xae, 0xab,
	0x75, 0xe3, 0xa3, 0x10, 0xc5, 0x2e, 0x99, 0x68, 0xce, 0x1b, 0xfc, 0x0c, 0xec, 0x0d, 0xaf, 0xd5,
	0x62, 0x1c, 0xa2, 0xd8, 0x22, 0xd6, 0x86, 0xd7, 0x79, 0x83, 0x5f, 0x81, 0xdb, 0x49, 0x2a, 0xfb,
	0xae, 0xda, 0xb2, 0x3b, 0xb6, 0xf5, 0x8d, 0x10, 0xc5, 0x4f, 0xe7, 0xa7, 0xc9, 0xfd, 0x1f, 0x24,
	0xfa, 0xe3, 0xc9, 0xa5, 0x0a, 0x10, 0x67, 0x88, 0x6b, 0xc0, 0x73, 0xb0, 0x07, 0xf4, 0x4d, 0xdd,
	0x9b, 0x1d, 0xeb, 0x95, 0x3a, 0x41, 0xf6, 0x49, 0xfc, 0x1a, 0xe0, 0x96, 0x0a, 0x7a, 0xc3, 0x24,
	0x13, 0x9d, 0x6f, 0x85, 0x28, 0x76, 0xe6, 0xc1, 0xb1, 0xde, 0xd5, 0x21, 0x45, 0xee, 0x35, 0x66,
	0xdf, 0x00, 0xfe, 0x6f, 0xf0, 0x19, 0x9c, 0x28, 0xad, 0x15, 0xef, 0x5b, 0xa9, 0x95, 0x2d, 0x32,
	0xdd, 0xf0, 0x3a, 0x55, 0x8c, 0x5f, 0xc0, 0x93, 0x1b, 0x46, 0xdb, 0xaa, 0xe9, 0x05, 0x95, 0x6b,
	0xde, 0x6a, 0x75, 0x83, 0xb8, 0x6a, 0x78, 0xb1, 0x9f, 0xe1, 0xe7, 0xe0, 0x7e, 0xa1, 0xeb, 0x6d,
	0x2f, 0x58, 0x25, 0xa8, 0x64, 0xfa, 0x04, 0xc6, 0xc4, 0xd9, 0xcf, 0x08, 0x95, 0x2c, 0x3a, 0x03,
	0x6b, 0xf0, 0x3d, 0x01, 0x6b, 0x71, 0xfe, 0x29, 0x7d, 0xe7, 0x8d, 0xf0, 0x04, 0x8c, 0xf7, 0x1f,
	0x17, 0x1e, 0x8a, 0x72, 0xb0, 0x07, 0x43, 0xec, 0xc0, 0xe4, 0x43, 0x5e, 0x96, 0x79, 0xf1, 0xd6,
	0x1b, 0x29, 0xb8, 0xca, 0x8a, 0x0b, 0x05, 0x48, 0x01, 0x59, 0x16, 0x85, 0x82, 0xb1, 0x82, 0x72,
	0x99, 0xa6, 0x59, 0x59, 0x7a, 0x86, 0x82, 0x37, 0xe7, 0xf9, 0xe5, 0x92, 0x64, 0x9e, 0x19, 0x7d,
	0x07, 0xf3, 0x33, 0x17, 0x5f, 0x1f, 0x71, 0x8d, 0x33, 0x98, 0x1e, 0x24, 0x0d, 0x2d, 0x79, 0xe0,
	0x07, 0x82, 0xe6, 0x03, 0xc1, 0x85, 0xf7, 0x6b, 0x17, 0xa0, 0xdf, 0xbb, 0x00, 0xfd, 0xd9, 0x05,
	0xe8, 0xc7, 0xdf, 0x60, 0x54, 0xdb, 0xfa, 0xa1, 0xbd, 0xfc, 0x17, 0x00, 0x00, 0xff, 0xff, 0x90,
	0x31, 0x2d, 0xb4, 0x77, 0x02, 0x00, 0x00,
}
